### ISSUE TITLE
[Question] How to add this plug-in work with selectize?

### ISSUE THREAD

**Issue by donhuvy** [jimmyngo/selectize-infinite_scroll#1]
Do I need re-build selectize.js?
What is simple way to add your plug-in to standalone seletize.js file?
Thank you!

**Comment by jimmyngo** [comment]
You don't need to rebuild selectize.js, but you need the file loaded so that it can add itself to the Selectize plugin system. If you want to add this plugin to a standalone file, you can probably just concatenate it to the end of selectize.js.

**Comment by donhuvy** [comment]
Thank friend, I will try your solution right now, then feed back later.
To be sure, is your plug-in compatible with current version of selectize ( https://github.com/selectize/selectize.js/releases/tag/v0.12.3 )?

**Comment by donhuvy** [comment]
It works!
